version: "1.0"
info:
  model: int-scaffold
packages:
- name: Ser_GH_0108Project
  gitServerName: srcGithubCtrl_Arti
  gitUrl: https://github.com/ArtiKhareIBM
  gitUsername: ArtiKhareIBM
  gitBranch: main
- name: AddIntsPackage
  gitServerName: src_AR_shared
  gitUrl: https://dev.azure.com/ArtiKhare/AddIntsPackage/_git
  gitUsername: ArtiKhare
  gitBranch: master
